/**
 * Main orchestration tool for creating and deploying a Shopware Frontends storefront
 *
 * Flow:
 * 1. Fetch template from GitHub (shopware/frontends)
 * 2. Apply branding (colors + logo)
 * 3. Create GitHub repo and push files
 * 4. Create Vercel project and trigger deployment
 */

import { fetchTemplate } from "../lib/template";
import { applyBranding } from "../lib/branding";
import { ensureRepoAndPush } from "../lib/github";
import { ensureVercelProjectAndDeploy } from "../lib/vercel";

export interface CreateStoreInput {
  storeId: string;
  templateRef: string;
  brand: {
    name: string;
    colors: Record<string, string>;
    logoSvg?: string;
  };
  git: {
    owner: string;
    repo: string;
    private: boolean;
  };
  vercel: {
    projectName: string;
    teamId?: string;
  };
}

export interface CreateStoreResult {
  ok: boolean;
  storeId: string;
  steps: {
    templateFetch: {
      ok: boolean;
      template: string;
      ref: string;
      fileCount: number;
    };
    branding: {
      ok: boolean;
      modifiedFiles: string[];
      warnings: string[];
    };
    github: {
      ok: boolean;
      repoUrl: string;
      repoCreated: boolean;
      commitSha: string;
      filesCommitted: number;
    };
    vercel: {
      ok: boolean;
      projectUrl: string;
      projectCreated: boolean;
      deploymentUrl: string | null;
      deploymentStatus: string | null;
    };
  };
  summary: {
    repoUrl: string;
    deploymentUrl: string | null;
    message: string;
  };
}

export async function createStoreAndDeploy(input: CreateStoreInput): Promise<CreateStoreResult> {
  const result: CreateStoreResult = {
    ok: false,
    storeId: input.storeId,
    steps: {
      templateFetch: { ok: false, template: "", ref: "", fileCount: 0 },
      branding: { ok: false, modifiedFiles: [], warnings: [] },
      github: { ok: false, repoUrl: "", repoCreated: false, commitSha: "", filesCommitted: 0 },
      vercel: { ok: false, projectUrl: "", projectCreated: false, deploymentUrl: null, deploymentStatus: null },
    },
    summary: { repoUrl: "", deploymentUrl: null, message: "" },
  };

  try {
    // Step 1: Fetch template from GitHub
    const templateResult = await fetchTemplate({
      template: "vue-starter-template-extended",
      ref: input.templateRef,
    });

    result.steps.templateFetch = {
      ok: true,
      template: templateResult.template,
      ref: templateResult.ref,
      fileCount: templateResult.files.length,
    };

    // Step 2: Apply branding to template files
    const brandingResult = applyBranding(templateResult.files, {
      colors: input.brand.colors,
      logoSvg: input.brand.logoSvg,
    });

    result.steps.branding = {
      ok: true,
      modifiedFiles: brandingResult.modifiedFiles,
      warnings: brandingResult.warnings,
    };

    // Step 3: Create GitHub repo and push files
    const githubResult = await ensureRepoAndPush(
      {
        owner: input.git.owner,
        repo: input.git.repo,
        private: input.git.private,
        description: `Shopware Frontends storefront for ${input.brand.name} (${input.storeId})`,
      },
      templateResult.files,
      `Initial commit: ${input.brand.name} storefront\n\nGenerated by frontends-mcp-server\nStore ID: ${input.storeId}`
    );

    result.steps.github = {
      ok: true,
      repoUrl: githubResult.repo.repoUrl,
      repoCreated: githubResult.repo.created,
      commitSha: githubResult.push.commitSha,
      filesCommitted: githubResult.push.filesCommitted,
    };

    // Step 4: Create Vercel project and trigger deployment
    const vercelResult = await ensureVercelProjectAndDeploy({
      projectName: input.vercel.projectName,
      teamId: input.vercel.teamId,
      framework: "nuxtjs",
      gitRepository: {
        type: "github",
        repo: `${input.git.owner}/${input.git.repo}`,
      },
    });

    result.steps.vercel = {
      ok: true,
      projectUrl: vercelResult.project.projectUrl,
      projectCreated: vercelResult.project.created,
      deploymentUrl: vercelResult.deployment?.deploymentUrl ?? null,
      deploymentStatus: vercelResult.deployment?.status ?? null,
    };

    // All steps completed successfully
    result.ok = true;
    result.summary = {
      repoUrl: githubResult.repo.repoUrl,
      deploymentUrl: vercelResult.deployment?.deploymentUrl ?? null,
      message: `Successfully created storefront "${input.brand.name}" (${input.storeId})`,
    };

    return result;
  } catch (error) {
    // Capture the error and return partial result
    const errorMessage = error instanceof Error ? error.message : String(error);
    result.summary.message = `Failed to create storefront: ${errorMessage}`;
    return result;
  }
}
